version: '3.3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DB: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      PMA_HOST: mysql
    ports:
      - 8080:80
